config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/about", to:"pages#about"
  get "/dashboard", to:"pages#dashboard"
  get "/signup", to:"users#new"
  post "/signup", to:"users#create"
  get 'login', to: 'sessions#new'
  resources :users, except: [:new]
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
  get 'pending', to: 'pages#pending'
  get 'processing', to: 'pages#processing'
  get 'completed', to: 'pages#completed'
  
  resources :documents do
    resources :routes
    post :forward_document
    post :decline_document
  end

# resources :routes do
  # resources :likes, only: [:create, :destroy]
# end
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/document.rb
class Document < ApplicationRecord
    belongs_to :user
    belongs_to :category
    belongs_to :section
    has_many :routes, dependent: :destroy
    accepts_nested_attributes_for :routes
    validates :name, presence: true, length: { minimum: 6 }
    validates :description, length: { maximum: 100 }
    enum :status, {
        created: 0,
        pending: 1,
        processing: 2,
        completed: 3,
        rejected: 4
    }
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
    before_action :set_documents, only: [:show, :edit, :update, :destroy]
    before_action :require_user
    before_action :require_same_user, only: [:destroy]

    def index
        @documents = Document.order(id: :desc)
    end

    def show
        @routes = @document.routes
    end

    def new
        @document = Document.new
    end

    def create
        @document = Document.new(document_params)
        @document.user = current_user 
        respond_to do |format|  
            if @document.save
                format.html{ redirect_to @document, notice: "You have successfully created a new document" }
            else
                format.turbo_stream { render turbo_stream: turbo_stream.replace(
                'remote_modal', partial: 'documents/form_modal', locals: {document: @document})}
                format.html { render :new, status: :unprocessable_entity, alert: "Error in creating new document" }
            end
        end
    end

    def edit
    end

    def update
        respond_to do |format|
            if @document.update(document_params)
                format.html { redirect_to @document, notice: "You have successfully edit a document!" }
            else
                format.turbo_stream { render turbo_stream: turbo_stream.replace(
                'remote_modal', partial: 'documents/form_modal', locals: {document: @document})}
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @document.destroy
        redirect_to documents_path, status: :see_other, notice: "You have successfully deleted a document!"
    end

    def preview
        @document = Document.find(params[:document_id])
        @route = Route.new
        respond_to do |format|
            format.turbo_stream
        end
    end

    def forward_document
      Documents::RouteHandler.call(destination: foward_document_params)
      
      respond_to do |format|
        format.html{ redirect_to documents_path, notice: "You have successfully routed a document" }
      end
        rescue DocumentForwardingException => e
        redirect_to request.path, error: e.forward_error_message
    end

    def decline_document
        Documents::RouteHandler.call(destination: decline_document_params)

        respond_to do |format|
            format.html{ redirect_to processing_path, notice: "You have declined a document" }
        end
        rescue DocumentForwardingException => e
            redirect_to request.path, error: e.decline_error_message
    end

    private
    
    def set_documents
        @document = Document.find(params[:id])
    end

    def document_params
        params.require(:document).permit(:name, :description, :category_id, :status, :section_id)
    end

    def foward_document_params
      params.require(:route).permit(:document_id, :destination_user_id, :remarks)
    end

    def decline_document_params
        params.require(:route).permit(:document_id, :destination_user_id, :remarks)
      end

    def require_same_user
        if current_user != @document.user && !current_user.admin?
            redirect_to @document, alert: "You can only edit or delete your own article"
        end   
    end

end

app/views/documents/_document.html.erb
<div id="<%= dom_id document %>">
  <%= link_to document_path(document.id), class: "list-group-item list-group-item-action", role: "button" do %>
    <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= document.name %></h5>
        <small> <%= time_ago_in_words(document.routes.last.updated_at) if document.routes.any? %> ago</small>
    </div>
    <h6> <span class="badge bg-success"><%= document.category.name %></span></h6>
    <p><%= document.description %></p>
  <% end %>   
</div>

app/views/documents/_form.html.erb
<%= bootstrap_form_for(document) do |f| %>
	<div class="modal-body">
			<%= f.select :category_id, Category.all.collect{ |p| [ p.name, p.id ]}, { prompt: "Choose document category"} %>
			<%= f.grouped_collection_select :section_id, Division.order(:name), :sections, :name, :id, :name, { prompt: "Choose origin"} %>
			<%= f.text_field :name %>
			<%= f.text_area :description %>
	</div>
	<div class="modal-footer">
			<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
			<%= f.submit class: "btn btn-primary", data: {action: "click->bs-modal#submitForm"} %>
	</div>

<% end %>

app/views/documents/_form_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"
        data-controller="bs-modal">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Create new document</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= render "form", document: document %>
        </div>
    </div>
    </div>
<% end %>

app/views/documents/_preview_doc.html.erb
<%= turbo_frame_tag "document_#{@document.id}" do %>
      <%= bootstrap_form_with(model: [@document, @route]) do |doc| %>
        <%= doc.static_control :name, label_class: "label_preview", wrapper: { class: 'd-flex flex-row m-3'}, value: @document.name %>
        <%= doc.static_control :description, label_class: "label_preview", wrapper: { class: 'd-flex flex-row m-3'}, value: @document.description %>
        <%= doc.static_control :user_id, label_class: "label_preview", wrapper: { class: 'd-flex flex-row m-3'}, value: @document.user.username %>
        <%= doc.static_control :category_id, label_class: "label_preview", wrapper: { class: 'd-flex flex-row m-3'}, value: @document.category.name %>
        <%= doc.static_control :status_id, label_class: "label_preview", wrapper: { class: 'd-flex flex-row m-3'}, value: @document.status.statusName %>
        <%= doc.submit "Accept", class: "btn btn-success" %>
        
      <% end %>.
  <% end %>

app/views/documents/completed.html.erb
<div class="row justify-content-center">
  <div class="col-6 p-3">
    <h4>Completed documents</h4>
    <div class="trackContainer">
       <div class="list-group p-1">
            <% @documents.each do |document| %>
                <% if document.status_id == 3 %>
                    <%= render 'documents/document', document: document %>
                <% end %>
            <% end %>
        </div> 
    </div>
  </div>
   <div class="col-6 p-3">
      <h4>Document Information</h4>
        <div id="doc_details">
        </div>
    </div>
</div>

app/views/documents/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render "form_modal", document: @document %>
<% end %>

app/views/documents/index.html.erb
   
<div class="row">
   <div class="d-flex justify-content-between">
    <h1> My document logs </h1>
    <div class="mt-2 p-2">
        <%= link_to "New log", new_document_path, class: "btn btn-success btn-lg", data: {controller: 'document-modal'} %>
    </div>
</div>
</div>
<div class="row justify-content-center my-3 mx-1">
  <div class="col-md-3">
      <h3> Created </h3>
      <div class="trackContainer" id="document_list">
          <div class="list-group p-1">
              <% @documents.each do |document| %>
                  <% if document.user == current_user && document.created? %>
                      <%= render document %>
                  <% end %>
              <% end %>
          </div> 
      </div>    
  </div>
  <div class="col-md-3">
      <h3> Pending </h3>
      <div class="trackContainer" id="document_list">
          <div class="list-group p-1">
              <% @documents.each do |document| %>
                  <% if document.user == current_user && document.pending?  %>
                      <%= render document %>
                  <% end %>
              <% end %>
          </div> 
      </div>    
  </div>
  <div class="col-md-3">
      <h3> Processing </h3>
      <div class="trackContainer">
          <div class="list-group p-1">
              <% @documents.each do |document| %>
                  <% if document.user == current_user && document.processing? %>
                      <%= render document %>
                  <% end %>
              <% end %>
          </div> 
      </div>    
  </div>
  <div class="col-md-3">
      <h3> Completed </h3>
      <div class="trackContainer">
          <div class="list-group p-1">
              <% @documents.each do |document| %>
                  <% if document.user == current_user && document.completed? %>
                      <%= render document %>
                  <% end %>
              <% end %>
          </div> 
      </div>    
  </div>
</div>

app/views/documents/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render "form_modal", document: @document %>
<% end %>

app/views/documents/preview.html.erb
<div class="row d-flex flex-lg-row flex-sm-column flex-xs-column">
  <div class="col-7 p-5 d-flex flex-column justify-content-center" style="height: 600px">
    <div class="document_controls">
    <h3 class="mb-3">Document Information: </h3>
      <%= form_with url: document_accept_path(@document), model: @document do |doc| %>
        <%= doc.text_field :name %>
        <%= doc.text_area :description %>
        <%= doc.text_field :user_id %>
        <%= doc.text_field :category_id %>
        <%= doc.text_field :status_id %>
        <%= doc.fields_for(:routes, Route.new) do |route| %>
          <%= route.text_area :remarks, value: 'received' %>
        <%= doc.submit "Accept", class: "btn btn-success" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/documents/preview.turbo_stream.erb
<%= turbo_stream.update "doc_details" do %>
  <%= render "documents/preview_doc", locals: { document: @document, route: @route } %>
<% end %>

app/views/documents/show.html.erb
<div class="row d-flex flex-lg-row flex-sm-column flex-xs-column">
  <div class="col-7 p-5 d-flex flex-column" style="height: 600px">
    <div class="document_list">
      <h3 class="mb-3">Document Information: </h3>
      <div class="row mb-1">
        <div class="col-lg-3 col-sm-12">
          <p><strong>Title: </strong></p>
        </div>
        <div class="col-lg-9 col-sm-12">
          <p><%= @document.name %></p>
        </div>
      </div>
      <div class="row mb-1">
        <div class="col-lg-3 col-sm-12">
          <p><strong>Description: </strong></p>
        </div>
        <div class="col-lg-9 col-sm-12">
          <p><%= @document.description %></p>
        </div>
      </div>
      <div class="row mb-1">
        <div class="col-lg-3 col-sm-12">
          <p><strong>Category: </strong></p>
        </div>
        <div class="col-lg-9 col-sm-12">
          <p> <span class="badge bg-success"><%= @document.category.name %></span></p>
        </div>
      </div>
       <div class="row mb-1">
        <div class="col-lg-3 col-sm-12">
          <p><strong>State: </strong></p>
        </div>
        <div class="col-lg-9 col-sm-12">
          <p> <%= @document.routes.last.state if @document.routes.any? %> </p>
        </div>
      </div>
      <div class="row mb-1">
        <div class="col-lg-3 col-sm-12">
          <p><strong>Status: </strong></p>
        </div>
        <div class="col-lg-9 col-sm-12">
          <p> <%= @document.status %> </p>
        </div>
      </div>
      <div class="row mb-1">
        <div class="col-lg-3 col-sm-12">
          <p><strong>Origin: </strong></p>
        </div>
        <div class="col-lg-9 col-sm-12">
          <p> Office of the Schools Division Superintendent </p>
        </div>
      </div>
      <div class="row mb-1">
        <% if logged_in? && (@document.user == current_user || current_user.admin?) %>
          <div class="d-grid gap-2 d-md-block">
            <% if !@document.routes.any? && @document.created?   %>
              <%= link_to "Forward to", new_document_route_path(@document), class: "btn btn-success", data: {controller: 'document-modal'} %>
            <% end %>
            <%= link_to "Edit", edit_document_path(@document), class: "btn btn-primary", data: {controller: 'document-modal'}  %>
            <%= link_to "Delete", document_path(@document), class: "btn btn-secondary", data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                      } %>
          </div>
        <% end %>  
      </div>
    </div>
  </div>
  <div class="col-5 p-5 mb-3">
    <h3 class="mb-3">Route Information: </h3>
      <ul class="list-group list-group-flush">
        <% @routes.each do |route| %>
          <li class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
              <p class="mb-1"> 
                to <%= route.destination_user == current_user ? "you" : route.destination_user.username %>
              </p>
              <small><%= route.created_at.to_fs(:short) %></small>
            </div>    
          </li>
        <% end %>
      </ul>
  </div>
</div>