config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/about", to:"pages#about"
  get "/dashboard", to:"pages#dashboard"
  get "/signup", to:"users#new"
  post "/signup", to:"users#create"
  get 'login', to: 'sessions#new'
  resources :users, except: [:new]
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
  get 'pending', to: 'pages#pending'
  get 'processing', to: 'pages#processing'
  get 'completed', to: 'pages#completed'
  
  resources :documents do
    resources :routes
    post :forward_document
    post :decline_document
  end

# resources :routes do
  # resources :likes, only: [:create, :destroy]
# end
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/route.rb
class Route < ApplicationRecord
	belongs_to :document
	belongs_to :destination_user, class_name: "User"
	validates :remarks, presence: false, length: { maximum: 100}
	enum :state, {
		forwarded: 0,
		received: 1,
		released: 2,
		declined: 3
	}   

	after_create :set_document_to_pending
	after_update :set_document_to_processing

	def set_document_to_pending
		document.update(status: :pending)
	end

	def set_document_to_processing
		document.update(status: :processing)
	end

end 

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
    before_action :require_user
    before_action :set_document, only: [:new, :create, :show, :edit]

    def index
        @routes = Route.order(id: :desc)
    end

    def show
        @route = Route.new
        @found_route = Route.find(params[:id])
        @routes = @document.routes
    end
    
    def new
        @route = Route.new
    end
    
    def create
        @route = Route.new(route_params)
        respond_to do |format|  
            if @route.save
                format.html{ redirect_to documents_path, notice: "You have successfully routed a document" }
            else
                format.turbo_stream { render turbo_stream: turbo_stream.replace(
                'remote_modal', partial: 'routes/form_modal', locals: {route: @route})}
                format.html { render :new, status: :unprocessable_entity, alert: "Error in routing a document" }
            end
        end
    end

    def edit
        @route = Route.find(params[:id])
    end

    def update
        @route = Route.find(params[:id])
        #if params[:state].present?
        #    @route.update(state: params[:state])
        #end
        #redirect_to @route, notice: "You successfully accepted a document!"
        if @route.update(route_params)
            redirect_to processing_path, notice: "You just accepted a document!"
        else
            redirect_to request.path, status: :unprocessable_entity, notice: "Error accepting document!"
        end
    end

    def destroy
        @route = Route.find(params[:id])
        if @route.destroy
            redirect_to pending_path, notice: "You have successfully rejected a document!"
        else
            redirect_to request.path, status: :unprocessable_entity, notice: "Error rejecting document!"
        end
    end

    private

    def route_params
        params.require(:route).permit(:document_id, :destination_user_id, :remarks, :state)
    end

    def set_document
        @document = Document.find(params[:document_id])
    end

end

app/views/routes/_document_route.html.erb
<div id="<%= dom_id route %>">
    <%= link_to document_route_path(route.document, route), class: "list-group-item list-group-item-action", role: "button" do %>
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= route.document.name %></h5>
            <small> <%= time_ago_in_words(route.updated_at) %> ago</small>
        </div>
        <h6> <span class="badge bg-success"><%= route.document.category.name %></span></h6>
    <% end %>
</div>

app/views/routes/_form.html.erb
<div class="modal-body">
    <%= bootstrap_form_for(:route, url: document_forward_document_path(), method: :post, remote: :true) do |f| %>
        <%= f.hidden_field :document_id, value: @document.id %>
        <%= f.select :destination_user_id, User.all.collect{ |u| [u.username, u.id]}, {prompt: "Forward to"} %>
        <%= f.text_area :remarks %>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= f.submit "Send", class: "btn btn-primary", data: {action: "click->bs-modal#submitForm"} %> 
    </div>
    <% end %>
</div>

app/views/routes/_form_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"
        data-controller="bs-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Route document</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <%= render "routes/form", locals: {route: @route, document: @document}  %>
        </div>
    </div>
    </div>
<% end %>

app/views/routes/edit.html.erb
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-6">
            <h1 class="text-center mb-3"> Route document </h1>

                <%= bootstrap_form_for(@route) do |f| %>
                    <%= f.fields_for :document do |r| %>
                        <%= r.select :category_id, Category.all.collect{ |p| [ p.name, p.id ]}, { prompt: "Choose document category"}, disabled: true  %>
                        <%= r.text_field :name, disabled: true %>
                        <%= r.text_area :description, disabled: true %>
                        <% if @route.action_id != 1 %>
                            <%= f.select :destination_user_id, User.all.collect{ |u| [u.username, u.id]}, {prompt: "Choose receiving user"} %>
                        <% end %>
                    <%= f.primary %>
                    <% end %>
                <% end %>
                    <%= link_to "Return", :back %>
                    
        </div>
    </div>
</div>

app/views/routes/index.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-md-3">
            <h3>To be received</h3>
             <div class="trackContainer">
                <% @routes.each do |route| %>
                    <% if logged_in? && (route.destination_user_id == current_user || current_user.admin?) %>
                    <% if route.action_id == 1 %>
                        <div class="list-group p-1">
                            <a href="routes/<%= route.id %>" class="list-group-item list-group-item-action" aria-current="true">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1"><%= route.document.name %></h5>
                                    <small> <%= time_ago_in_words(route.created_at) %> ago</small>
                                </div>
                                <h6> <span class="badge bg-success"><%= route.document.category.name %></span></h6>
                                <small>from <%= route.document.user.username %></small>
                            </a>
                        </div>
                    <% end %>
                    <% end %>
                <% end %>
            </div>    
        </div>
            <div class="col-md-3">
            <h3>Just received</h3>
            <div class="trackContainer">
                 <% @routes.each do |route| %>
                    <% if logged_in? && (route.destination_user_id == current_user || current_user.admin?) %>
                    <% if route.action_id == 3 %>
                        <div class="list-group p-1">
                            <a href="routes/<%= route.id %>" class="list-group-item list-group-item-action" aria-current="true">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1"><%= route.document.name %></h5>
                                    <small> <%= time_ago_in_words(route.created_at) %> ago</small>
                                </div>
                                <h6> <span class="badge bg-success"><%= route.document.category.name %></span></h6>
                                <small>from <%= route.document.user.username %></small>
                            </a>
                        </div>
                    <% end %>
                    <% end %>
                <% end %>
            </div>
        </div>
        <div class="col-md-3">
            <h3> Released </h3>
            <div class="trackContainer">
                 <% @routes.each do |route| %>
                    <% if logged_in? && (route.destination_user_id == current_user || current_user.admin?) %>
                    <% if route.action_id == 4 %>
                        <div class="list-group p-1">
                            <a href="routes/<%= route.id %>" class="list-group-item list-group-item-action" aria-current="true">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1"><%= route.document.name %></h5>
                                    <small> <%= time_ago_in_words(route.created_at) %> ago</small>
                                </div>
                                <h6> <span class="badge bg-success"><%= route.document.category.name %></span></h6>
                                <small>from <%= route.document.user.username %></small>
                            </a>
                        </div>
                    <% end %>
                    <% end %>
                <% end %>
            </div>
        </div>
        <div class="col-md-3">
            <h3> Forwarded </h3>
             <div class="trackContainer">
               <% @routes.each do |route| %>
                    <% if logged_in? && (route.destination_user_id == current_user || current_user.admin?) %>
                    <% if route.action_id == 2 %>
                        <div class="list-group p-1">
                            <a href="routes/<%= route.id %>" class="list-group-item list-group-item-action" aria-current="true">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1"><%= route.document.name %></h5>
                                    <small> <%= time_ago_in_words(route.created_at) %> ago</small>
                                </div>
                                <h6> <span class="badge bg-success"><%= route.document.category.name %></span></h6>
                                <small>from <%= route.document.user.username %></small>
                            </a>
                        </div>
                    <% end %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
            </div>
        </div>
        </div>
</div>

app/views/routes/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render "routes/form_modal", locals: {route: @route, document: @document } %>
<% end %>

app/views/routes/show.html.erb
<div class="row d-flex flex-lg-row flex-sm-column flex-xs-column">
  <div class="col-7 p-5 d-flex flex-column" style="height: 600px">
    <div class="document_list">
      <h3 class="mb-3">Document Information: </h3>
      <div class="row mb-1">
        <div class="col-lg-3 col-sm-12">
          <p><strong>Title: </strong></p>
        </div>
        <div class="col-lg-9 col-sm-12">
          <p><%= @found_route.document.name %></p>
        </div>
      </div>
      <div class="row mb-1">
        <div class="col-lg-3 col-sm-12">
          <p><strong>Description: </strong></p>
        </div>
        <div class="col-lg-9 col-sm-12">
          <p><%= @found_route.document.description %></p>
        </div>
      </div>
      <div class="row mb-1">
        <div class="col-lg-3 col-sm-12">
          <p><strong>Category: </strong></p>
        </div>
        <div class="col-lg-9 col-sm-12">
          <p> <span class="badge bg-success"><%= @found_route.document.category.name %></span></p>
        </div>
      </div>
      <div class="row mb-1">
        <div class="col-lg-3 col-sm-12">
          <p><strong>State: </strong></p>
        </div>
        <div class="col-lg-9 col-sm-12">
          <p> <%= @found_route.state %> </p>
        </div>
      </div>
      <div class="row mb-1">
        <div class="col-lg-3 col-sm-12">
          <p><strong>Status: </strong></p>
        </div>
        <div class="col-lg-9 col-sm-12">
          <p> <%= @found_route.document.status %> </p>
        </div>
      </div>
      <div class="row mb-1">
        <div class="col-lg-3 col-sm-12">
          <p><strong>Origin: </strong></p>
        </div>
        <div class="col-lg-9 col-sm-12">
          <p> <%= @found_route.document.section.name %> </p>
        </div>
      </div>
      <div class="row row-cols-lg-auto g-2 align-items-center mb-1">
        <% if logged_in? && (@found_route.destination_user == current_user || current_user.admin?) %>
          <% if @found_route.forwarded? %>
            <%= form_tag(document_route_path(@document, @found_route), method: :patch, remote: true) do %>
              <%= hidden_field_tag :_method, :patch %>
              <%= hidden_field_tag "route[state]", "received" %>
              <div class="col-12">
                <input type="submit" value="Accept" class="btn btn-primary">
              </div>
            <% end %>
              <div class="col-12">
                <%= form_for(:route, url: document_decline_document_path(@document), method: :post, remote: :true) do |f| %>
                  <%= f.hidden_field :document_id, value: @document.id %>
                  <%= f.hidden_field :status, value: Route.states[:declined] %>
                  <%= f.hidden_field :destination_user_id, value:  @document.routes.count > 1  ? @document.routes.second_to_last.destination_user_id : @document.user_id  %>
                  <div class="col-12">
                    <%= f.submit "Decline", class: "btn btn-secondary", data: { confirm: "Decline #{@document.name}?"} %>
                  </div>
                <% end %>
              </div>
          <% end %>
              <div class="col-12">
                <% if @document.routes.last.received? %>
                  <%= link_to "Forward to", new_document_route_path(@document), class: "btn btn-success", data: {controller: 'document-modal'} %>
                <% end %>
              </div>
        <% end %>  
      </div>
    </div>
  </div>
  <div class="col-5 p-5 mb-3">
    <h3 class="mb-3">Route Information: </h3>
      <ul class="list-group list-group-flush">
        <% @routes.each do |route| %>
          <li class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
              <p class="mb-1">
                to <%= route.destination_user == current_user ? "you" : route.destination_user.username %>
              </p>
              <small><%= route.created_at.to_fs(:short) %></small>
            </div>    
          </li>
        <% end %>
      </ul>
  </div>
</div>