config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/about", to:"pages#about"
  get "/dashboard", to:"pages#dashboard"
  get "/signup", to:"users#new"
  post "/signup", to:"users#create"
  get 'login', to: 'sessions#new'
  resources :users, except: [:new]
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
  get 'pending', to: 'pages#pending'
  get 'processing', to: 'pages#processing'
  get 'completed', to: 'pages#completed'
  
  resources :documents do
    resources :routes
    post :forward_document
    post :decline_document
  end

# resources :routes do
  # resources :likes, only: [:create, :destroy]
# end
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 45 }
    validates_uniqueness_of :name
    has_many :documents
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    before_action :require_admin, except: [:index, :show]

    def index
        @categories = Category.all
    end

    def show
        @category = Category.find(params[:id])
        @documents = @category.documents
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(params.require(:category).permit(:name))
        if @category.save
            redirect_to categories_path, notice: "You have successfully created a new category!"
        else
            render :new, status: :unprocessable_entity
        end   
    end

    def edit
        
    end

    def update
        if @category.update(params.require(:category).permit(:name))
            redirect_to @category, notice: "You have successfully edit a category!"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @category.destroy
        redirect_to categories_path, status: :see_other, notice: "You have successfully deleted a category!"
    end

    private

    def set_category
        @category = Category.find(params[:id])
    end


end

app/views/categories/_form.html.erb
   <%= bootstrap_form_with(model: @category, local: true) do |f| %>
        <%= f.text_field :name %>
        <%= f.primary %>
        <%= link_to "Return", @category %>
    <% end %>

app/views/categories/edit.html.erb
<div class="container mt-3">
    <div class="row">
        <div class="col-6 justify-content-center">

           <%= render 'form' %>

        </div>
    </div>
</div>

app/views/categories/index.html.erb
<div class="container mt-3">
    <h1>Document Categories</h1>

    <div class="row row-cols-2 row-cols-md-3 g-4 mt-3">
    <% if current_user.admin? %>
    <div class="col">
            <div class="card text-bg-light position-relative">
            <div class="card-body">
                <h5 class="card-title">
                    <span class="px-2"><%= image_tag "plus.png", height: 24 %></span>
                    <%= link_to "Add New Doc Type", new_category_path, class: 'link-dark text-decoration-none stretched-link' %>
                </h5>
            </div>
            </div>
        </div>
    <% end %>
    <% @categories.each do | category | %>
        <div class="col">
            <a href="/categories/<%= category.id %>" class="text-decoration-none">
                <div class="card text-bg-primary">
                <div class="card-body">
                    <h5 class="card-title position-relative"><%=category.name %>
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"><%= pluralize(category.documents.count, '')  %></span>
                    </h5>
                </div>
                </div>
            </a>
        </div>
    <% end %>
        
    </div>
   
</div>

app/views/categories/new.html.erb
<div class="container mt-3">
    <div class="row">
        <div class="col-6 justify-content-center">

         <%= render 'form' %>

        </div>
    </div>
</div>

app/views/categories/show.html.erb
<div class="container mt-3">
    <h1>Showing <%= @category.name %></h1>
    <% if logged_in? && current_user.admin? %>
        <%= link_to "Edit", edit_category_path(@category), class: "btn btn-primary" %>
        <%= link_to "Delete", category_path(@category), 
            data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
        <%= link_to "Return", categories_path %>
    <% end %>

    <% @documents.each do |document| %>
    <div class="row justify-content-center mt-4">
        <div class="col-6">
            <div class="card">
                <small class="card-header"><i>Pending</i></small>
                    <div class="card-body">
                        <h5 class="card-title"> <%= document.name %>
                         <span class="badge bg-secondary"><%= document.category.name %></span></h5>
                        <p class="card-text"><%= document.description %></p>
                        <% if logged_in? && document.user == current_user || current_user.admin? %>
                            <%= link_to "Edit", edit_document_path(document) , class: "btn btn-primary"%>
                            <%= link_to "Delete", document_path(document),
                                data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %> 
                        <% end %>
                    </div>
            </div>
        </div>
    </div>   
    <% end %>

    
</div>    