config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/about", to:"pages#about"
  get "/dashboard", to:"pages#dashboard"
  get "/signup", to:"users#new"
  post "/signup", to:"users#create"
  get 'login', to: 'sessions#new'
  resources :users, except: [:new]
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
  get 'pending', to: 'pages#pending'
  get 'processing', to: 'pages#processing'
  get 'completed', to: 'pages#completed'
  
  resources :documents do
    resources :routes
    post :forward_document
    post :decline_document
  end

# resources :routes do
  # resources :likes, only: [:create, :destroy]
# end
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_messages.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8 messages">
            <% flash.each do |name, msg| %>
                <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show mt-3" role="alert">
                    <strong><%= msg %></strong> 
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark navbar-expand-lg ">
  <div class="container-fluid">
    <%= link_to root_path, class: 'navbar-brand pe-5' do %>
      <%= image_tag "bitmap_Layer 1.png", width: 38 %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Users", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Categories", categories_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link" href="#">Documents</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Offices</a>
        </li>
      </ul>
      <div>
      <% if logged_in? %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" >
              <%= current_user.admin? ? 'Admin' : 'User' %> [<%= current_user.username %>]
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
              </li>
              <li>
                 <%= link_to "Log Out", logout_path, class: "dropdown-item log-out", data: {turbo_method: :delete} %>
              </li>
            </ul>
          </li>
        </ul>
      <% else %>
        <%= link_to "Log In", login_path, class: "btn btn-outline-success" %>
        <%= link_to "Sign Up", signup_path, class: "btn btn-success" %>
      <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
    <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
        <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white sidebar">
            <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                <li class="nav-item">
                    <%= link_to dashboard_path, class: "nav-link align-middle px-0" do %>
                        <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span>
                    <% end %>
                </li>
                <li class="nav-item">
                    <%= link_to documents_path, class: "nav-link align-middle px-0 my-logs" do %>
                        <i class="fs-4 bi-file-text"></i> <span class="ms-1 d-none d-sm-inline">My logs</span>
                    <% end %>
                </li>
                <li>
                    <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                        <span class="ms-1 d-none d-sm-inline">Route Logs</span> </a>
                    <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                        <li class="ps-2 w-100">
                            <%= link_to pending_path, class: "nav-link px-0" do %>
                                <i class="fs-4 bi-exclamation-square"></i> <span class="ms-1 d-none d-sm-inline">Pending</span>
                            <% end %>
                        </li>
                        <li class="ps-2 w-100">
                            <%= link_to processing_path, class: "nav-link px-0" do %>
                                <i class="fs-4 bi-recycle"></i> <span class="ms-1 d-none d-sm-inline">Processing</span>
                            <% end %>
                        </li>
                        <li class="ps-2 w-100">
                            <%= link_to completed_path, class: "nav-link px-0" do %>
                                <i class="fs-4 bi-recycle"></i> <span class="ms-1 d-none d-sm-inline">Completed</span>
                            <% end %>
                        </li>
                       
                    </ul>
                </li>
            </ul>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocumentTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
  <%= render 'layouts/navigation' %>

  <main>
  <%= turbo_frame_tag 'remote_modal'  %>
    <div class="container-fluid p-0">
        <%= yield :home %>
        <% if action_name == "new" && controller_name == "sessions" %>
          <%= yield :login_page %>
        <% elsif action_name == "new" && controller_name == "users" %>
          <%= yield :signup_page %>
        <% else %>
        <div class="row">
            <%= render 'layouts/sidebar' unless action_name == "home" %>
            <div class="col-auto col-md-9 col-xl-10">
              <%= render 'layouts/messages' %>  
              <%= yield %>
            </div>
        </div>
        <% end %>
    </div>
  </main>
  </body>

</html>